config/routes.rb
Rails.application.routes.draw do
  resources :payments, except: [:edit, :update, :destroy]
  resources :enquiries
  resources :messages
  resources :year_levels do
    member do
      post :add
      delete :remove
    end
  end
  resources :subjects do
    member do
      post :add
      delete :remove
    end
  end
  resources :profiles
  post 'search', to: 'profiles#search'
  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :profile_subjects
  has_many :subjects, through: :profile_subjects
  has_many :profile_year_levels
  has_many :year_levels, through: :profile_year_levels

  geocoded_by :full_street_address
  after_validation :geocode

  mount_uploader :picture, ProfilePictureUploader

  after_create :add_tutor_role

  def full_street_address
    [street, suburb, state, postcode, country].compact.join(', ')
  end

  def full_name
    [first_name, last_name].join(' ')
  end

  def add_tutor_role
    self.user.add_role :tutor
  end

  def self.search(search)
    where("subject LIKE ?", "%#{search}%")
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def search
    @profile_search = params[:profile]
    @distance = @profile_search['distance']
    @subject = Subject.find(@profile_search['subject'])
    @year_level = YearLevel.find(@profile_search['year_level'])
    @postcode = @profile_search['postcode']
    @tutors = @subject.profiles.near(@postcode + ', Australia', @distance.to_i, :units => :km) & @year_level.profiles.near(@postcode + ', Australia', @distance.to_i, :units => :km)
  end
  # GET /profiles
  # GET /profiles.json
  def index
    if params[:search]
      @subject = Subject.where(name: params[:search])
      @profiles = @subject.profiles
    else
      @profiles = Profile.all
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @subjects = Subject.order(:name)
    @year_levels = YearLevel.all
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    respond_to do |format|
      if @profile.save
        @profile.user.add_role :tutor
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :qualification, :years_experience, :hourly_rate, :picture, :bio, :street, :suburb, :state, :postcode, :country, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :qualification %>
    <%= f.input :years_experience %>
    <%= f.input :hourly_rate %>
    <%= f.input :picture %>
    <%= f.input :bio %>
    <%= f.input :street %>
    <%= f.input :suburb %>
    <%= f.input :state %>
    <%= f.input :postcode %>
    <%= f.input :country, priority: ['Australia'] %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Qualification</th>
      <th>Years experience</th>
      <th>Hourly rate</th>
      <th>Picture</th>
      <th>Bio</th>
      <th>Street</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.qualification %></td>
        <td><%= profile.years_experience %></td>
        <td><%= profile.hourly_rate %></td>
        <td><%= profile.picture %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.street %></td>
        <td><%= profile.suburb %></td>
        <td><%= profile.state %></td>
        <td><%= profile.postcode %></td>
        <td><%= profile.country %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>Create your profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/search.html.erb
<% if @tutors.any? %>
  <div class="row">
    <div class="col-md-6">
      <h2>Filters</h2>
      <hr>
      <%= simple_form_for :profile, url: search_path, html: { class: 'form-inline'} do |f| %>
      <h4>Subjects</h4>
      <%= f.input :subject, collection: Subject.all, selected: @subject.id, label: false, input_html: { required: true } %>
      <hr>
      <h4>Year levels</h4>
      <%= f.input :year_level, collection: YearLevel.all, selected: @year_level.id, label:false, input_html: { required: true } %>
      <hr>
      <h4>Distance</h4>
        <%= f.input :postcode, label: false, placeholder: 'Enter postcode', input_html: { required: true, value: @postcode } %>
        <%= f.input :distance, label: 'km radius:', collection: [2,5,10,15,20], selected: @distance %>
        <%= f.submit 'Update', class: 'btn btn-info' %>
      <% end %>
      <hr>
      <div class="row">
        <% @tutors.each do |tutor| %>
          <div class="col-md-6">
            <div class="card">
              <img class="card-img-top" src="<%= tutor.picture %>" alt="<%= tutor.full_name %>" width="100%">
              <div class="card-block">
                <h4 class="card-title"><%= tutor.full_name %></h4>
                <p class="card-text"><%= tutor.bio %></p>
                <%= link_to 'More info', profile_path(tutor), class: 'btn btn-info' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div id="map"></div>
      <script>
        function initMap() {
          var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 10,
            center: {lat: -33.9, lng: 151.2}
          });

          setMarkers(map);
        }

        function setMarkers(map) {

          var image = {
            url: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png',
            // This marker is 20 pixels wide by 32 pixels high.
            size: new google.maps.Size(20, 32),
            // The origin for this image is (0, 0).
            origin: new google.maps.Point(0, 0),
            // The anchor for this image is the base of the flagpole at (0, 32).
            anchor: new google.maps.Point(0, 32)
          };
          // Shapes define the clickable region of the icon. The type defines an HTML
          // <area> element 'poly' which traces out a polygon as a series of X,Y points.
          // The final coordinate closes the poly by connecting to the first coordinate.
          var shape = {
            coords: [1, 1, 1, 20, 18, 20, 18, 1],
            type: 'poly'
          };
          <% @tutors.each do |tutor| %>
            var marker = new google.maps.Marker({
              position: {lat: <%= tutor.latitude %>, lng: <%= tutor.longitude %>},
              map: map,
              icon: image,
              shape: shape,
              title: "<%= tutor.full_name %>"
            });
            <% end %>
          }

      </script>

      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAel2sOgAjOR1qEWpL8Qe0eYiP2DYNtyk8&callback=initMap"
        async defer></script>

  </div>
</div>
<% else %>
  <p>Sorry, there are no tutors in your area. Try your search again.</p>
<% end %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-4">
    <div class="card card-block">
      <h4 class="card-title">
  <%= @profile.first_name %> <%= @profile.last_name %> <%= link_to 'Message me', new_message_path(receiver: @profile.user.id), class: 'btn btn-warning' %></h4>

<%= link_to 'Upgrade account', new_payment_path, class: 'btn btn-primary' %>

<p>
  <strong>Qualification:</strong>
  <%= @profile.qualification %>
</p>

<p>
  <strong>Years experience:</strong>
  <%= @profile.years_experience %>
</p>

<p>
  <strong>Hourly rate:</strong>
  <%= @profile.hourly_rate %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @profile.picture %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<p>
  <strong>Street:</strong>
  <%= @profile.street %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @profile.suburb %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @profile.postcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @profile.country %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

    </div>
  </div>
  <div class="col-md-6">
    <div class="card card-block">
      <h4 class="card-title">My Subjects</h4>
      <% @subjects.each do |subject| %>
        <% if @profile.subjects.include?(subject) %>
          <%= button_to subject.name, remove_subject_path(subject), method: :delete, class: 'btn btn-success disabled' %>
        <% else %>
          <%= button_to subject.name, add_subject_path(subject), class: 'btn btn-danger' %>
        <% end %>
      <% end %>
    </div>
    <div class="card card-block">
      <h4 class="card-title">My Year Levels</h4>
      <% @year_levels.each do |year_level| %>
        <% if @profile.year_levels.include?(year_level) %>
          <%= button_to year_level.name, remove_year_level_path(year_level), method: :delete, class: 'btn btn-success' %>
        <% else %>
          <%= button_to year_level.name, add_year_level_path(year_level), class: 'btn btn-danger' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<!-- <div id="map"></div> -->
  <script>
  handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 0,
      "lng": 0,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
  </script>

  <script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=AIzaSyAel2sOgAjOR1qEWpL8Qe0eYiP2DYNtyk8&libraries=geometry&language=&hl=&region="></script>