config/routes.rb
Rails.application.routes.draw do
  resources :payments, except: [:edit, :update, :destroy]
  resources :enquiries
  resources :messages
  resources :year_levels do
    member do
      post :add
      delete :remove
    end
  end
  resources :subjects do
    member do
      post :add
      delete :remove
    end
  end
  resources :profiles
  post 'search', to: 'profiles#search'
  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/year_level.rb
class YearLevel < ActiveRecord::Base
  has_many :profile_year_levels
  has_many :profiles, through: :profile_year_levels
end

app/controllers/year_levels_controller.rb
class YearLevelsController < ApplicationController
  before_action :set_year_level, only: [:show, :edit, :update, :destroy, :add, :remove]

  def add
    current_user.profile.year_levels << @year_level
    redirect_to :back
  end

  def remove
    current_user.profile.year_levels.delete(@year_level)
    redirect_to :back
  end
  # GET /year_levels
  # GET /year_levels.json
  def index
    @year_levels = YearLevel.all
  end

  # GET /year_levels/1
  # GET /year_levels/1.json
  def show
  end

  # GET /year_levels/new
  def new
    @year_level = YearLevel.new
  end

  # GET /year_levels/1/edit
  def edit
  end

  # POST /year_levels
  # POST /year_levels.json
  def create
    @year_level = YearLevel.new(year_level_params)

    respond_to do |format|
      if @year_level.save
        format.html { redirect_to @year_level, notice: 'Year level was successfully created.' }
        format.json { render :show, status: :created, location: @year_level }
      else
        format.html { render :new }
        format.json { render json: @year_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /year_levels/1
  # PATCH/PUT /year_levels/1.json
  def update
    respond_to do |format|
      if @year_level.update(year_level_params)
        format.html { redirect_to @year_level, notice: 'Year level was successfully updated.' }
        format.json { render :show, status: :ok, location: @year_level }
      else
        format.html { render :edit }
        format.json { render json: @year_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /year_levels/1
  # DELETE /year_levels/1.json
  def destroy
    @year_level.destroy
    respond_to do |format|
      format.html { redirect_to year_levels_url, notice: 'Year level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_year_level
      @year_level = YearLevel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def year_level_params
      params.require(:year_level).permit(:name, :description)
    end
end

app/helpers/year_levels_helper.rb
module YearLevelsHelper
end

app/views/year_levels/_form.html.erb
<%= simple_form_for(@year_level) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/year_levels/edit.html.erb
<h1>Editing Year Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @year_level %> |
<%= link_to 'Back', year_levels_path %>

app/views/year_levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Year Levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @year_levels.each do |year_level| %>
      <tr>
        <td><%= year_level.name %></td>
        <td><%= year_level.description %></td>
        <td><%= link_to 'Show', year_level %></td>
        <td><%= link_to 'Edit', edit_year_level_path(year_level) %></td>
        <td><%= link_to 'Destroy', year_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Year level', new_year_level_path %>

app/views/year_levels/new.html.erb
<h1>New Year Level</h1>

<%= render 'form' %>

<%= link_to 'Back', year_levels_path %>

app/views/year_levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @year_level.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @year_level.description %>
</p>

<%= link_to 'Edit', edit_year_level_path(@year_level) %> |
<%= link_to 'Back', year_levels_path %>